function(enable_doxygen)
    option(ENABLE_DOXYGEN "Enable doxygen doc builds of source" ON)
    if (ENABLE_DOXYGEN)
        set(DOXYGEN_CALLER_GRAPH YES)
        set(DOXYGEN_CALL_GRAPH YES)
        set(DOXYGEN_EXTRACT_ALL YES)
        set(DOXYGEN_PRIVATE YES)
        set(DOXYGEN_GENERATE_LATEX YES)
        set(DOXYGEN_LATEX_OUTPUT pdf)
        set(DOXYGEN_HIDE_SCOPE_NAMES YES)
        set(DOXYGEN_PROJECT_NAME "Profiler")
        set(DOXYGEN_PROJECT_NUMBER "v${VERSION}")
        set(DOXYGEN_DISABLE_INDEX NO)
        set(DOXYGEN_GENERATE_TREEVIEW YES)
        set(DOXYGEN_JAVADOC_BANNER NO)
        set(DOXYGEN_JAVADOC_AUTOBRIEF NO)
        set(DOXYGEN_JAVADOC_BLOCK NO)
        set(DOXYGEN_FULL_PATH_NAMES NO)
        set(DOXYGEN_STRIP_CODE_COMMENTS NO)
        set(DOXYGEN_HTML_HEADER ${PROJECT_SOURCE_DIR}/documentation/Doxygen/html/header.html)
        set(DOXYGEN_HTML_FOOTER ${PROJECT_SOURCE_DIR}/documentation/Doxygen/html/footer.html)
#        set(DOXYGEN_HTML_STYLESHEET ${PROJECT_SOURCE_DIR}/documentation/Doxygen/customdoxygen.css)
        find_package(Doxygen REQUIRED dot)
        doxygen_add_docs(doxygen-docs ${PROJECT_SOURCE_DIR}/src ${PROJECT_SOURCE_DIR}/documentation/Doxygen ALL)
        install(DIRECTORY ${CMAKE_CURRENT_BINARY_DIR}/html DESTINATION share/docs)
    endif ()
endfunction()