name: Deploy Docs

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**.h'
      - 'src/**.cpp'
      - 'documentation/**.md'
      - '.github/workflows/deploy_docs.yml'

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CXX: /usr/bin/g++-10
    steps:
      - uses: actions/checkout@v2

      - name: Install Doxygen
        # Install doxygen from apt
        run: |
          sudo apt-get update
          sudo apt-get -y install doxygen graphviz

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory.
        run: >
          cmake -B ${{github.workspace}}/build 
          -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} 
          -DCMAKE_CXX_COMPILER=${{ env.CXX }} 
          -DBUILD_TESTS=OFF
          -DBUILD_DOXYGEN=ON

      - name: Build
        # Build your program with the given configuration
        run: >
          cmake --build ${{github.workspace}}/build 
          --config ${{env.BUILD_TYPE}} 
          --target doxygen-docs

      - name: Update Doxygen Pages
        run: |
          mkdir -p ${{github.workspace}}/docs
          cp -rf ${{github.workspace}}/build/html/* ${{github.workspace}}/docs/.
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add --force docs
          git stash
          git remote update
          git checkout gh-pages
          git rm -rf docs
          git stash pop
          git reset
          git add --force docs
          git commit --allow-empty -m "Update Doxygen documentation"
          git push
