name: Check unit test coverage 

on:
  workflow_dispatch:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  conda:
    runs-on: ubunutu-latest 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Create environment
      uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-activate-base: false
        environment-file: myenv.yml
        python-version: 3.9 
        activate-environment: myenv

    - name: Package list
      shell: bash -l {0} 
      run: | 
        conda info
        conda list 

    - name: Gcov
      shell: bash -l {0}
      run: | 
        conda install gcov

    - name: Lcov
      shell: bash -l {0}
      run: | 
        conda install lcov

  build:
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        compiler: [
          {c: gcc-10, cpp: g++-10, fortran: gfortran-10}
        ]
    
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Configure CMake 
      run: > 
        cmake -B ${{github.workspace}}/build 
        -DCMAKE_C_COMPILER=${{ matrix.compiler.c }}
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} 
        -DCMAKE_Fortran_COMPILER=${{ matrix.compiler.fortran }}
        -DBUILD_TESTS=ON
        -DBUILD_FORTRAN_TESTS=OFF
        -DINCLUDE_GTEST=ON
        -DCMAKE_CXX_FLAGS="--coverage" 
        -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON 
        -DENABLE_DOXYGEN=OFF 

    - name: Build 
      run: cmake --build ${{github.workspace}}/build

    - name: Make 
      working-directory: ${{github.workspace}}/build 
      run: make 

    - name: Run tests 
      working-directory: ${{github.workspace}}/build  
      run: ctest 

  run:
    runs-on: ubuntu-latest 

    steps:

    - name: Run Gcov 
      working-directory: ${{github.workspace}}/build
      run: gcov -j -m ${{github.workspace}}/build/src/c++/CMakeFiles/profiler.dir/*.gcno

    - name: Run Lcov
      working-directory: ${{github.workspace}}/build 
      run: lcov --capture --directory ${{github.workspace}}/build/src/c++/CMakeFiles/profiler.dir --output-file coverage.info
           
    - name: Generate html
      working-directory: ${{github.workspace}}/build
      run: genhtml coverage.info --output-directory out

  