name: Check unit test coverage 

on:
  workflow_dispatch:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ] 

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      fail-fast: false
      matrix:
        compiler: [
          {c: gcc-10, cpp: g++-10, fortran: gfortran-10}
        ]

    defaults: 
      run:
        shell: bash
        working-directory: ${{github.workspace}}/build

    steps:
    - uses: actions/checkout@v2

    - name: Create conda environment
      uses: conda-incubator/setup-miniconda@v2
      with: 
        auto-activate-base: false
        python-version: 3.9 
        channels: conda-forge, defaults
        activate-environment: myenv

    - name: Install Lcov
      shell: -l {0}
      run: conda install lcov

    - name: Configure CMake 
      run: > 
        cmake -B ${{github.workspace}}/build 
        -DCMAKE_C_COMPILER=${{ matrix.compiler.c }}
        -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cpp }} 
        -DCMAKE_Fortran_COMPILER=${{ matrix.compiler.fortran }}
        -DBUILD_TESTS=ON
        -DBUILD_FORTRAN_TESTS=OFF
        -DINCLUDE_GTEST=ON
        -DCMAKE_CXX_FLAGS="--coverage" 
        -DCMAKE_CXX_OUTPUT_EXTENSION_REPLACE=ON 
        -DENABLE_DOXYGEN=OFF 

    - name: Build 
      run: cmake --build ${{github.workspace}}/build

    - name: Make 
      run: make 

    - name: Run tests 
      run: ctest 

    - name: Run Gcov 
      run: gcov -j -m ${{github.workspace}}/build/src/c++/CMakeFiles/profiler.dir/*.gcno

    - name: Run Lcov
      shell: -l {0}
      run: lcov --capture --directory ${{github.workspace}}/build/src/c++/CMakeFiles/profiler.dir --output-file coverage.info
           
    - name: Generate html
      shell: -l {0}
      run: genhtml coverage.info --output-directory out

  