name: Run Unit Tests

on:
  workflow_run:
    workflows: [ "Build Dynamically" ] 
    branches: [ main ]
    types:
      - completed
  #workflow_dispatch:
  # push:
  #   branches: [ main ]
  # pull_request: 
  #   branches: [ main ]

env: 
  BUILD_TYPE: Debug

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        threads: [1, 4]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo "Triggering workflow was a success, running unit tests..."
      - uses: actions/checkout@v2

    ## DOwnload the binary artifact here???? <<<
      - uses: actions/download-artifact@v3 
        with:
          name: ym-artifact
          path: ${{ github.workspace }}

      # Run tests 
      - name: "Test (${{ matrix.threads }} threads)"
        env:
          OMP_NUM_THREADS: ${{ matrix.threads }}
        working-directory: ${{github.workspace}}/build
        run: ctest -VV -C ${{env.BUILD_TYPE}}

  dont-run:
    runs-on: ubunutu-latest 
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo "Triggering workflow failed"